---
commonOverlays:
  - name: Inject line comments via merge
    query:
      - metadata.annotations['my.custom.annotation/fake']
      - metadata.annoations['service.beta.kubernetes.io/aws-load-balancer-type']
    value: "" # inject a line comment
    action: merge
  - name: Inject a line comment via format
    query: spec.containers[0].image
    value: "%s" # inject a line comment
    action: format
  - name: Inject header, footer, and line comments via merge
    query: metadata.labels
    value:
      # inject a header comment
      app.kubernetes.io/owner: Jeff Smith  # inject a line comment
      app.kubernetes.io/purpose: static-webpage  # inject another line comment
      # inject a footer comment
    action: merge
yamlFiles:
  - name: Set of Kubernetes manifests from upstream
    path: ./examples/kubernetes/manifests