---
commonOverlays:
  - name: Inject line comments via merge
    query:
      - metadata.annotations['my.custom.annotation/fake']
      - metadata.annoations['service.beta.kubernetes.io/aws-load-balancer-type']
    value: "%v" # inject a line comment
    action: merge
  - name: Inject a line comment via replace
    query: spec.containers[0].image
    value: new-image:latest # old value was: %v
    action: replace
  - name: Inject head, foot, and line comments via merge
    query: metadata.labels
    value:
      # inject a head comment
      app.kubernetes.io/owner: Jeff Smith  # inject a line comment
      app.kubernetes.io/purpose: static-webpage  # inject another line comment
      # inject a foot comment
    action: merge
yamlFiles:
  - name: Set of Kubernetes manifests from upstream
    path: ./examples/kubernetes/manifests